# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idt < Formula
  desc "A fast, ergonomic CLI tool for working with various ID formats"
  homepage "https://github.com/sh-cho/idt"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sh-cho/idt/releases/download/0.1.6/idt_darwin_x86_64.tar.gz"
      sha256 "8c9ceb69cc33be7b774c9187b608447687e8fb8d44d6b94c9aea658c26bd85b7"

      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sh-cho/idt/releases/download/0.1.6/idt_darwin_arm64.tar.gz"
      sha256 "78a873a5be9d0ee6d3507355f54de2a9f59a9f5625c0ff3d3b3e3042919987a9"

      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sh-cho/idt/releases/download/0.1.6/idt_linux_x86_64.tar.gz"
      sha256 "3f42139c8086b51aa0ad340935159544c67ae016ef8940b98ad15d3cbd718b29"
      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sh-cho/idt/releases/download/0.1.6/idt_linux_arm64.tar.gz"
      sha256 "1abac82820ca9b438d067002c10e35ddf93fce8d6b41e712d9b94d1bb311d3fc"
      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
      end
    end
  end

  test do
    system "#{bin}/idt", "--version"
  end
end
