# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idt < Formula
  desc "A fast, ergonomic CLI tool for working with various ID formats"
  homepage "https://github.com/sh-cho/idt"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sh-cho/idt/releases/download/0.1.8/idt_darwin_x86_64.tar.gz"
      sha256 "33ad059767229c989f4b8f68f1866ea15f62d073735d2526e808ce48c248357d"

      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sh-cho/idt/releases/download/0.1.8/idt_darwin_arm64.tar.gz"
      sha256 "6d96a57481ac286c4d7a27e8c246d1d3ad0729cf50af73893702293beebed345"

      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sh-cho/idt/releases/download/0.1.8/idt_linux_x86_64.tar.gz"
      sha256 "69e2e00cf3db6d8dd32095b89afbbae71bc9b429baf5f9fdbc504b7543bdcb45"
      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sh-cho/idt/releases/download/0.1.8/idt_linux_arm64.tar.gz"
      sha256 "7d913144cde6a9ba3c6dc59a2ea02186a99bb29253724ac2c050e6f78c285215"
      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
      end
    end
  end

  test do
    system "#{bin}/idt", "--version"
  end
end
