# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Idt < Formula
  desc "A fast, ergonomic CLI tool for working with various ID formats"
  homepage "https://github.com/sh-cho/idt"
  version "0.1.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sh-cho/idt/releases/download/0.1.15/idt_darwin_x86_64.tar.gz"
      sha256 "a7f6df35f604fb8c5f990d9f6dc67bb9e7c44b1498a35f77155efd976e79e664"

      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
        system "#{bin}/idt", "manpage", man1.to_s
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sh-cho/idt/releases/download/0.1.15/idt_darwin_arm64.tar.gz"
      sha256 "cdcf74569103ec2068e97616d9161f23763736d9a41d3b27dc593dc13c9b260d"

      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
        system "#{bin}/idt", "manpage", man1.to_s
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sh-cho/idt/releases/download/0.1.15/idt_linux_x86_64.tar.gz"
      sha256 "48b4fd983fb825dd348455d47e141495e65a307e2bb6fbbc7afa9ec8fec569f3"
      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
        system "#{bin}/idt", "manpage", man1.to_s
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sh-cho/idt/releases/download/0.1.15/idt_linux_arm64.tar.gz"
      sha256 "f48f8f09eb06e52f44fe43079c4d24356a3840a684665be7ef1135f045af9e39"
      define_method(:install) do
        bin.install "idt"
        generate_completions_from = proc do |shell|
          IO.popen("#{bin}/idt completions #{shell}", &:read)
        end
        (bash_completion/"idt").write generate_completions_from.call("bash")
        (zsh_completion/"_idt").write generate_completions_from.call("zsh")
        (fish_completion/"idt.fish").write generate_completions_from.call("fish")
        system "#{bin}/idt", "manpage", man1.to_s
      end
    end
  end

  test do
    system "#{bin}/idt", "--version"
  end
end
